Repository lilycollinsbnb/aoperat_property_valuation_website, pull requests merged in 2023-04, with the labels that each got.

#3 popup
  package-lock.json
  package.json
  src/assets/img/logo.svg
  src/assets/img/popup-bg.jpg
  src/assets/scss/style.scss
  src/components/contact-form.js
  src/components/free-trial-popup.js
  src/content/pages/index.md
  src/templates/contact-page.js
  src/templates/index-page.js
Labels: enhancement

#4 Update Post “2023-02-02-jakie-dokumenty-są-potrzebne-przy-wycenie-nieruchomości”
  src/content/posts/2023-02-02-jakie-dokumenty-są-potrzebne-przy-wycenie-nieruchomości.md
Labels: netlify-cms/pending_review

#5 Create Post “2023-04-14-jak-zostać-rzeczoznawcą-majątkowym”
  src/content/posts/2023-04-14-jak-zostać-rzeczoznawcą-majątkowym.md
  static/assets/374f86e6-35da-4871-a3c5-1ee267c83b79.jpg
  static/assets/pexels-rodnae-productions-8293647.jpg
Labels: netlify-cms/pending_review

#6 Create Post “2023-04-14-co-sprawdzić-przed-zakupem-mieszkania”
  src/content/posts/2023-04-14-co-sprawdzić-przed-zakupem-mieszkania.md
  static/assets/panele-winylowe-w-lazience2-2048x1448.jpg
  static/assets/pexels-kindel-media-7578939.jpg
  static/assets/wentylacja-w-kuchni-okap-kratka-wentylacyjna-i-mozliwe-problemy-114082.jpg
Labels: netlify-cms/pending_review

#7 Create Post “2023-04-14-kodeks-etyki-zawodowej”
  src/content/posts/2023-04-14-kodeks-etyki-zawodowej.md
  static/assets/10d9e808-0444-45ff-bb3a-1cc0af06907c.jpg
  static/assets/pexels-pixabay-159832.jpg
Labels: netlify-cms/pending_review

#11 Create Post “2023-04-14-co-to-jest-wartość-nieruchomości”
  src/content/posts/2023-04-14-co-to-jest-wartość-nieruchomości.md
  static/assets/4a648ac1-8a19-459f-9684-c7d1ddb0311b.jpg
  static/assets/josh-appel-netpasr-bmq-unsplash.jpg
Labels: netlify-cms/pending_review

#12 Create Post “2023-04-14-co-to-jest-operat-szacunkowy”
  src/content/posts/2023-04-14-co-to-jest-operat-szacunkowy.md
  static/assets/2c9b980c-6d8a-4ef1-a573-736061cc10e7.jpg
  static/assets/pexels-pixabay-357514.jpg
Labels: netlify-cms/pending_review

#9 Create Post “2023-04-14-czy-dla-zakupu-lub-sprzedaży-mieszkania-musimy-mieć-wycenę-w-formie-operatu-szacunkowego”
  src/content/posts/2023-04-14-czy-dla-zakupu-lub-sprzedaży-mieszkania-musimy-mieć-wycenę-w-formie-operatu-szacunkowego.md
  static/assets/pexels-expect-best-323780.jpg
  static/assets/real-estate-gde5fbc1b3_1920.jpg
Labels: netlify-cms/pending_review

#10 Create Post “2023-04-14-jakie-są-cele-sporządzenie-wyceny-nieruchomości-w-formie-operatów-szacunkowych”
  src/content/posts/2023-04-14-jakie-są-cele-sporządzenie-wyceny-nieruchomości-w-formie-operatów-szacunkowych.md
  static/assets/322f447b-3702-4f4f-b9e1-14b36d03032a.jpg
  static/assets/7b696319-2260-43a3-8f33-4807a20b08f5.jpg
  static/assets/pexels-expect-best-323780.jpg
Labels: netlify-cms/pending_review

#17 Update Post “2023-04-14-co-to-jest-wartość-nieruchomości”
  src/content/posts/2023-04-14-co-to-jest-wartość-nieruchomości.md
Labels: netlify-cms/pending_review

#18 Update Post “2023-04-14-kodeks-etyki-zawodowej”
  src/content/posts/2023-04-14-kodeks-etyki-zawodowej.md
Labels: netlify-cms/draft
